// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD50ZTIcoPcR4t-Wi7bB0pjI9VovjH6Ylg',
    appId: '1:161365904133:web:ce350cc1de861e889f856c',
    messagingSenderId: '161365904133',
    projectId: 'tasknest-c583d',
    authDomain: 'tasknest-c583d.firebaseapp.com',
    storageBucket: 'tasknest-c583d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoGjaPwEl_b1HChzVAu96xBmIWjYdnQOA',
    appId: '1:161365904133:android:90fb8e11f6f446089f856c',
    messagingSenderId: '161365904133',
    projectId: 'tasknest-c583d',
    storageBucket: 'tasknest-c583d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUr91jtPoWjA4HyVR-3uSKQHHRz8PGbI',
    appId: '1:161365904133:ios:e58948c1023832aa9f856c',
    messagingSenderId: '161365904133',
    projectId: 'tasknest-c583d',
    storageBucket: 'tasknest-c583d.firebasestorage.app',
    iosBundleId: 'com.example.tasknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHUr91jtPoWjA4HyVR-3uSKQHHRz8PGbI',
    appId: '1:161365904133:ios:e58948c1023832aa9f856c',
    messagingSenderId: '161365904133',
    projectId: 'tasknest-c583d',
    storageBucket: 'tasknest-c583d.firebasestorage.app',
    iosBundleId: 'com.example.tasknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD50ZTIcoPcR4t-Wi7bB0pjI9VovjH6Ylg',
    appId: '1:161365904133:web:2b3d6d583fa111a29f856c',
    messagingSenderId: '161365904133',
    projectId: 'tasknest-c583d',
    authDomain: 'tasknest-c583d.firebaseapp.com',
    storageBucket: 'tasknest-c583d.firebasestorage.app',
  );
}
